### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by mrpunkdasilva** [Design-and-Code/support#516]
### Name

Gustavo Henrique de Jesus da Silva

### Discord Username (if applicable)

Mr. Nullus#6058

### Additional Context

First of all I must say that the premise is incredible and I want to join you, because I am passionate about technology and how it can change people's lives. I'm looking forward to what I'm going to learn and I'm willing to contribute as much as I can. I thank you for your attention!

**Comment by FabianaCampanari** [comment]
Name
Fabiana Campanari

Discord Username (if applicable)
Fabiana Campanari#9413

Additional Context
First of all I must say that the premise is incredible and I want to join you, because I am passionate about technology and how it can change people's lives. I'm looking forward to what I'm going to learn and I'm willing to contribute as much as I can. I thank you for your attention!

**Comment by mrpunkdasilva** [comment]
@FabianaCampanari olá! receio que você seguiu o procedimento errado para ser membra, já que deve-se criar uma nova issue sobre **invitation**. Ou seja:

- Click em `New Issue`
- Em seguida escolha a opção `Please invite me to the GitHub Community Organization`
- Coloque os dados que são pedidos
- Por último espere o bot responsável por fazer o **invite** mandar o convite
